# Environment-specific overrides
# This file allows different configurations for dev/test/prod

# Development overrides (default when no environment specified)
services:
  database:
    environment:
      POSTGRES_DB: impactbot_v2_dev
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./database/seed-data:/docker-entrypoint-initdb.d/seed
    ports:
      - "5434:5432"

  cache:
    volumes:
      - redis_dev_data:/data
    ports:
      - "6380:6379"

  backend:
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
      DATABASE_URL: postgresql://postgres:${DB_PASSWORD:-secure_development_password_2024}@database:5432/impactbot_v2_dev
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/logs:/app/logs
      - ./backend/src:/app/src  # Enable hot reload in dev
    command: npm run dev

volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local